add report 'MultilevelCurrentness'
GIScience/ohsome-quality-analyst pull request #403
Opened 2022-08-06 15:17 UTC by Gigaszi

### Description
Add new report 'MultilevelCurrentness'.

### Corresponding issue
None

### New or changed dependencies
- None

### Checklist
- [ ] I have updated my branch to `main` (e.g. through `git rebase main`)
- [ ] My code follows the [style guide](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#style-guide) and was checked with [pre-commit](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#pre-commit) before committing
- [ ] I have commented my code
- [ ] I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-analyst/blob/main/docs/development_setup.md#tests)
- [ ] I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CHANGELOG.md)

2022-08-08 13:26 UTC, matthiasschaub requested changes

2022-08-08 13:26 UTC, matthiasschaub commented on website/website/index.html
> +						<option value="MultilevelCurrentness">Multilevel Mapping Saturation</option>
```suggestion
						<option value="MultilevelCurrentness">Multilevel Currentness</option>
```

2022-08-18 15:22 UTC, matthiasschaub commented on workers/ohsome_quality_analyst/reports/multilevel_currentness/metadata.yaml
> +    buildings, land-use/land-cover, points of interest and infrastructure.
```suggestion
    This report shows the currentness of four major map features (https://wiki.openstreetmap.org/wiki/Map_features):
    buildings, land-use and land-cover, points of interest and infrastructure.
```

2022-08-18 15:23 UTC, matthiasschaub commented on workers/ohsome_quality_analyst/reports/multilevel_currentness/metadata.yaml
> +      The general currentness for central elements in this region is low indicating a very early stage of the data.
```suggestion
      The general currentness for major map features in this region is low indicating a very early stage of the data.
```

2022-08-18 15:23 UTC, matthiasschaub commented on workers/ohsome_quality_analyst/reports/multilevel_currentness/metadata.yaml
> +      to determine the suitability of this region.
```suggestion
      The currentness of major map features in this region is mediocre. The results for each indicator should be reviewed
      to determine the suitability of this region.
```

2022-08-18 15:23 UTC, matthiasschaub commented on workers/ohsome_quality_analyst/reports/multilevel_currentness/metadata.yaml
> +      Most of the central elements were edited in recent years. This indicates a high currentness in this region.
```suggestion
      Most of the major map features were edited in recent years. This indicates a high currentness in this region.
```

2022-09-03 13:23 UTC, Gigaszi commented on workers/ohsome_quality_analyst/reports/multilevel_currentness/metadata.yaml
> +      The general currentness for central elements in this region is low indicating a very early stage of the data.
Done

2022-09-03 13:23 UTC, Gigaszi commented on workers/ohsome_quality_analyst/reports/multilevel_currentness/metadata.yaml
> +      to determine the suitability of this region.
Done

2022-09-03 13:23 UTC, Gigaszi commented on workers/ohsome_quality_analyst/reports/multilevel_currentness/metadata.yaml
> +      Most of the central elements were edited in recent years. This indicates a high currentness in this region.
Done

2022-09-11 11:56 UTC, matthiasschaub requested changes
Good addition to our new set of reports! The changelog needs to be updated, since a new release has been made. Once done this PR can be merged.

2022-09-11 19:04 UTC, Gigaszi commented
Done

2022-09-12 08:42 UTC, matthiasschaub approved these changes

2022-09-12 08:43 UTC, merged