MappingSaturation: add classification and plot creation for over 100% results
GIScience/ohsome-quality-analyst pull request #479
Opened 2023-02-09 18:34 UTC by Gigaszi

### Corresponding issue
Closes #282, #283

### New or changed dependencies
- None

### Checklist
- [ ] I have updated my branch to `main` (e.g. through `git rebase main`)
- [ ] My code follows the [style guide](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#style-guide) and was checked with [pre-commit](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#pre-commit) before committing
- [ ] I have commented my code
- [ ] I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-analyst/blob/main/docs/development_setup.md#tests)
- [ ] I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CHANGELOG.md)

2023-02-09 19:10 UTC, Gigaszi commented
![105](https://user-images.githubusercontent.com/74006329/217905983-41788a9a-3f06-414d-81ee-09fbc607e4a1.svg)
![water_area](https://user-images.githubusercontent.com/74006329/217906004-70270767-90f5-4101-8d05-b191a419b3c2.svg)
![forest_area](https://user-images.githubusercontent.com/74006329/217906027-166ee9ce-4ace-4ce2-ae67-d6aee87c61c4.svg)

These are some examples of the plots with a value over 1.

2023-02-14 13:41 UTC, hn437 requested changes
File: indicator.py
The additions are good, but I would keep the else statement at the end of the elif statements to catch unexpected values should they unexpectedly occure 

File: test_indicator_mapping_saturation.py
no further change requested

2023-02-14 13:41 UTC, hn437 commented on workers/ohsome_quality_analyst/indicators/mapping_saturation/indicator.py
> -        else:
I would keep the else statement at the end of the elif statements to catch unexpected values in case they occure

2023-03-07 09:07 UTC, matthiasschaub approved these changes
Thanks for this addition. I would squash existing commits into one.

2023-03-07 12:59 UTC, hn437 approved these changes

2023-03-07 14:09 UTC, merged