Update MapAction layers and POC report
GIScience/ohsome-quality-analyst pull request #56
Opened 2021-06-11 15:49 UTC by ddebarros-mapaction

Please add the **type of change** as label. If your PR is not ready for review and merge, please add `🚧 ` to the PR title.

### Description
The main change concerns the update of Map Action layers filters. We also changed the MapActionPoc report to be more consistent with this new layer definition.

### Corresponding issue
Closes #43 

### New or changed dependencies
-

### Checklist
- [ ] I have updated my branch to `main` (e.g. through `git rebase main`)
- [X] My code follows the [style guide](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#style-guide) and was checked with [pre-commit](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#pre-commit) before committing
- [X] I have commented my code
- ~I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-analyst/blob/main/docs/development_setup.md#tests)~
- [ ] I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CHANGELOG.md)

Please check all finished tasks. If some tasks do not apply to your PR, please cross their text out (by using `~...~`) and remove their checkboxes.

2021-06-11 15:51 UTC, ddebarros-mapaction commented
Not sure if I should add this modification to the CHANGELOG

2021-06-15 12:30 UTC, matthiasschaub commented
@ddebarros-mapaction I have a general question about this PR: What is the reason to include the OSM type `relations` in the filter query?
I ask because this can lead to performance issue on the ohsome API side.

The share of objects of relation elements with the tag highway is very low (https://taginfo.openstreetmap.org/keys/highway). Also the OSM Wiki states that the element relation should not be used with the tag highway. The same is in part true for the other keys. Although there are often more objects of type relation.

On the syntax part, I would remove the whitespace around the operators such as the equal sign (https://docs.ohsome.org/ohsome-api/stable/filter.html).

You can include this in the CHANGELOG.md. Just put in the PR title and link to it.

Otherwise this looks good to me!

2021-06-16 16:50 UTC, ddebarros-mapaction commented
Hello @matthiasschaub , thanks for the review. Just updated the two files (layer_definitions and CHANGELOG) with your recommendations.

Indeed, the type:relation is not indispensable. I first added it because some big lakes are represented with this type so I added it to be exhaustive. As this happened for the other layers as well I added everywhere in addition to type:way. 

In any case, we can live without it and it won't affect the quality report significantly.

2021-06-22 11:05 UTC, matthiasschaub approved these changes

2021-06-22 11:07 UTC, matthiasschaub submitted a review, later dismissed

2021-06-26 17:09 UTC, ddebarros-mapaction commented
Hello @matthiasschaub, just saw that there was a conflict concerning the CHANGELOG file. Let me know if it's OK now.

2021-06-28 07:17 UTC, matthiasschaub submitted a review, later dismissed

2021-06-28 07:18 UTC, matthiasschaub approved these changes

2021-06-28 08:17 UTC, ddebarros-mapaction commented
a new change on the main branch CHANGELOG was made. I had to resolve the conflict :/

2021-06-28 09:50 UTC, matthiasschaub approved these changes

2021-06-28 09:52 UTC, joker234 requested changes

2021-06-28 09:52 UTC, joker234 commented on CHANGELOG.md
> +- Implement combine_indicators() as Concrete Method of the Base Class Report ([53])
```suggestion
- Implement combine_indicators() as Concrete Method of the Base Class Report ([#53])
```

2021-06-28 09:52 UTC, joker234 commented on CHANGELOG.md
> +
```suggestion
```

2021-06-28 09:53 UTC, matthiasschaub submitted a review, later dismissed

2021-06-28 09:53 UTC, matthiasschaub approved these changes

2021-06-28 09:57 UTC, matthiasschaub approved these changes

2021-06-28 10:00 UTC, matthiasschaub approved these changes

2021-06-28 10:02 UTC, matthiasschaub approved these changes

2021-06-28 10:09 UTC, matthiasschaub commented
@ddebarros-mapaction Yes this happens a lot to me as well with small changes after a review or merge with the main branch. I am going ahead an merge this branch now. Cheers :+1:

2021-06-28 10:10 UTC, merged