mapping-saturation: change axis label of plot to aggregation type
GIScience/ohsome-quality-analyst pull request #611
Opened 2023-06-27 11:28 UTC by Gigaszi

### Description
y-axis of plot now has the aggregation type as label and not just "Value"

### Corresponding issue
Closes #588

### Checklist
- [ ] I have updated my branch to `main` (e.g. through `git rebase main`)
- [ ] My code follows the [style guide](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#style-guide) and was checked with [pre-commit](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#pre-commit) before committing
- [ ] I have commented my code
- [ ] I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-analyst/blob/main/docs/development_setup.md#tests)
- [ ] I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CHANGELOG.md)

Please check all finished tasks. If some tasks do not apply to your PR, please cross their text out (by using `~...~`) and remove their checkboxes.

2023-07-01 19:48 UTC, Gigaszi commented
the problem here is that indicators with attached data don't have an endpoint. So we either have to use something else to label the axis in general or we use "Value" in this case and the endpoint for all others accordingly

2023-07-03 13:09 UTC, matthiasschaub requested changes

2023-07-03 13:09 UTC, matthiasschaub commented on workers/ohsome_quality_analyst/indicators/mapping_saturation/indicator.py
> +            fig.update_yaxes(title_text="Value")
use `topic.aggregation_type` after #600 is merged

2023-07-11 13:48 UTC, matthiasschaub requested changes

2023-07-11 13:49 UTC, matthiasschaub submitted a review, later dismissed

2023-07-11 14:23 UTC, matthiasschaub approved these changes

2023-07-11 14:40 UTC, merged